services:
  mailhog:
    restart: unless-stopped
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
  api:
    restart: unless-stopped
    depends_on:
      - mailhog
    image: fcc-api
    env_file:
      - .env
    environment:
      - MAILHOG_HOST=mailhog
      - HOST=0.0.0.0
    ports:
      - '3000:3000'
