version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    command: mongod --replSet rs0
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: unless-stopped

  api:
    build:
      context: ./api # Point to the local directory with the API source code
    depends_on:
      - mongo
      - mailhog
    ports:
      - '3000:3000'
    environment:
      COOKIE_DOMAIN: yourdomain.com
      HOME_LOCATION: http://localhost:8000
      API_LOCATION: http://localhost:3000
      CHALLENGE_EDITOR_API_LOCATION: http://localhost:3200
      CHALLENGE_EDITOR_CLIENT_LOCATION: http://localhost:3300
      MONGOHQ_URL: mongodb://mongo:27017/freecodecamp?directConnection=true
      MAILHOG_HOST: mailhog
      HOST: 0.0.0.0
    command: >
      bash -c "
      pnpm install &&
      pnpm run seed &&
      pnpm run develop"
    restart: unless-stopped

  client:
    build:
      context: ./client # Point to the local directory with the client source code
    ports:
      - '8000:8000'
    environment:
      API_LOCATION: http://localhost:3000
      HOME_LOCATION: http://localhost:8000
    command: pnpm run develop -- -H '0.0.0.0'
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mongo_data:
